# Site settings
title: 'Cooking Analytics'
description: 'My name is Miguel Gaspar and the blog purpose is to provide information on the value and how to build IoT and Big Data solutions, providing business, architectural and technical guidance that can be useful to developers, architects and top level business managers. '
keywords: analytics,big data,iot,social innovation,bi,business intelligence,ctools,pentaho,real-time,realtime,live,insights,analysis,dashboards,artificial intelligence,machine learning'
url: 'http://mfgaspar.github.io'
baseurl: '/'
google_analytics: 'UA-75757763-1'
#disqus_shortname: 'mfgaspar'

author:
  name: 'Miguel Gaspar'
  email: miguel.ferreira.gaspar@gmail.com
  twitter_username: migfgaspar
  facebook_username: miguel.ferreira.gaspar
  github_username:  mfgaspar
  linkedin_username:  mfgaspar
  
defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
